name: noctur
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  uuid: ^3.0.6
  firebase_core: ^1.16.0
  firebase_storage: ^10.2.15
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  rxdart: ^0.27.3
  flutter_svg: ^1.0.3
  flutter_riverpod: ^1.0.3
  fake_cloud_firestore: ^1.2.2
  equatable: ^2.0.3
  go_router: ^3.1.1
  google_sign_in: ^5.3.0
  salomon_bottom_bar: ^3.3.1
  image_picker: ^0.8.5+3
  path_provider: ^2.0.10
  flex_color_scheme: ^5.0.1
  shared_preferences: ^2.0.15
  styles:
    path: ./packages/styles
  input_validator:
    path: ./packages/input_validator
  optional: ^6.1.0+1
  super_rich_text: ^1.0.0
  flutter_portal: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/svgs/
    - assets/imgs/
    - assets/imgs/logos/
    - assets/imgs/games/
